"""Smoke tests that exercise the sidecar against the real wireviz engine."""

from __future__ import annotations

import base64
import io

import pytest
from fastapi.testclient import TestClient

from wireviz_gui_sidecar.app import create_app


SIMPLE_YAML = """\
connectors:
  X1:
    type: D-Sub
    subtype: female
    pinlabels: [DCD, RX, TX, DTR, GND, DSR, RTS, CTS, RI]
  X2:
    type: Molex KK 254
    subtype: female
    pinlabels: [GND, RX, TX]

cables:
  W1:
    gauge: 0.25 mm2
    length: 0.2
    color_code: DIN
    wirecount: 3
    shield: true

connections:
  -
    - X1: [5,2,3]
    - W1: [1,2,3]
    - X2: [1,3,2]
  -
    - X1: 5
    - W1: s
"""


@pytest.fixture
def client():
    return TestClient(create_app())


def test_health(client):
    r = client.get("/health")
    assert r.status_code == 200
    body = r.json()
    assert body["status"] == "ok"
    assert "wireviz" in body


def test_parse_returns_svg_png_and_bom(client):
    r = client.post("/parse", json={"yaml": SIMPLE_YAML, "formats": ["svg", "png", "tsv"]})
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["svg"].lstrip().startswith("<")
    assert "png_base64" in body and body["png_base64"]
    assert body["tsv"] and "\t" in body["tsv"]


def test_png_round_trip_via_extract(client):
    # Render with embedded YAML, then post the PNG bytes back to /extract.
    r = client.post("/render/png", json={"yaml": SIMPLE_YAML, "embed_yaml": True})
    assert r.status_code == 200
    png_bytes = r.content
    files = {"file": ("harness.png", io.BytesIO(png_bytes), "image/png")}
    r2 = client.post("/extract", files=files)
    assert r2.status_code == 200
    assert "connectors:" in r2.json()["yaml"]


def test_extract_404_on_unembedded_png(client):
    r = client.post("/render/png", json={"yaml": SIMPLE_YAML, "embed_yaml": False})
    assert r.status_code == 200
    files = {"file": ("plain.png", io.BytesIO(r.content), "image/png")}
    r2 = client.post("/extract", files=files)
    assert r2.status_code == 404


def test_parse_surfaces_user_yaml_errors(client):
    r = client.post("/parse", json={"yaml": "not: [valid wireviz", "formats": ["svg"]})
    assert r.status_code in (400, 422)


# ---- /parse-multipart with image asset uploads ---------------------


# 4x4 transparent PNG, generated by Pillow (so it's actually valid — a
# hand-rolled 1x1 was rejected at load time, leading to silent image-drop
# in the SVG output and bogus tests). We don't ship binary fixtures.
TINY_PNG = bytes.fromhex(
    "89504e470d0a1a0a0000000d4948445200000004000000040806000000a9f19e7e"
    "0000000c49444154789c6360a01c000000440001d7e348fd0000000049454e44ae"
    "426082"
)


YAML_WITH_IMAGE = """\
connectors:
  X1:
    pincount: 4
    image:
      src: cross-section.png
      width: 100
  X2:
    pincount: 4

cables:
  W1:
    wirecount: 4
    length: 1

connections:
  -
    - X1: [1-4]
    - W1: [1-4]
    - X2: [1-4]
"""


def test_parse_multipart_resolves_uploaded_asset(client):
    r = client.post(
        "/parse-multipart",
        data={"yaml": YAML_WITH_IMAGE, "formats": "svg", "embed_yaml": "true"},
        files=[("files", ("cross-section.png", TINY_PNG, "image/png"))],
    )
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["svg"].lstrip().startswith("<")
    # Verify the upload actually got embedded into the SVG (not a broken
    # reference). embed_svg_images inlines raster images as data URIs.
    assert "data:image/png;base64," in body["svg"]


def test_parse_multipart_without_files_still_works(client):
    # The simple no-asset case must keep working through the multipart
    # endpoint — the frontend uses it as the single code path.
    r = client.post(
        "/parse-multipart",
        data={"yaml": SIMPLE_YAML, "formats": "svg"},
    )
    assert r.status_code == 200, r.text
    assert r.json()["svg"].lstrip().startswith("<")


def test_parse_multipart_missing_asset_surfaces_engine_error(client):
    # If the YAML references an image that the user didn't upload, the
    # engine raises and we surface that as a 422 (not a silent miss).
    r = client.post(
        "/parse-multipart",
        data={"yaml": YAML_WITH_IMAGE, "formats": "svg"},
    )
    assert r.status_code == 422
    assert "cross-section.png" in r.json()["detail"]


def test_render_png_multipart_preserves_iTXt(client):
    r = client.post(
        "/render/png-multipart",
        data={"yaml": YAML_WITH_IMAGE, "embed_yaml": "true"},
        files=[("files", ("cross-section.png", TINY_PNG, "image/png"))],
    )
    assert r.status_code == 200
    # Ensure the embed_yaml round-trip still works through the multipart path.
    extract = client.post(
        "/extract",
        files={"file": ("harness.png", io.BytesIO(r.content), "image/png")},
    )
    assert extract.status_code == 200
    assert "X1" in extract.json()["yaml"]


def test_render_svg_multipart_resolves_uploaded_asset(client):
    r = client.post(
        "/render/svg-multipart",
        data={"yaml": YAML_WITH_IMAGE},
        files=[("files", ("cross-section.png", TINY_PNG, "image/png"))],
    )
    assert r.status_code == 200
    assert r.headers["content-type"].startswith("image/svg+xml")
    body = r.content.decode("utf-8")
    assert body.lstrip().startswith("<")
    # Same data-URI inlining we verified in the parse path.
    assert "data:image/png;base64," in body


YAML_TWO_IMAGES = """\
connectors:
  X1:
    pincount: 2
    image:
      src: a.png
      width: 64
  X2:
    pincount: 2
    image:
      src: b.png
      width: 64

cables:
  W1:
    wirecount: 2
    length: 0.1

connections:
  -
    - X1: [1-2]
    - W1: [1-2]
    - X2: [1-2]
"""


def test_parse_multipart_handles_multiple_uploads(client):
    r = client.post(
        "/parse-multipart",
        data={"yaml": YAML_TWO_IMAGES, "formats": "svg"},
        files=[
            ("files", ("a.png", TINY_PNG, "image/png")),
            ("files", ("b.png", TINY_PNG, "image/png")),
        ],
    )
    assert r.status_code == 200, r.text
    body = r.json()
    # Both images should be inlined as data URIs in the SVG.
    assert body["svg"].count("data:image/png;base64,") >= 2


def test_parse_multipart_sanitises_filename_against_traversal(client):
    # The sidecar's spool function strips any directory components from
    # the upload filename — it uses Path(filename).name as the on-disk
    # target. A YAML reference to ../etc/passwd would therefore not
    # resolve, but the upload itself doesn't escape the tempdir.
    yaml = """\
connectors:
  X1:
    pincount: 1
    image:
      src: passwd.png
cables:
  W1:
    wirecount: 1
    length: 0.1
connections:
  -
    - X1: 1
    - W1: 1
"""
    # Submit an upload whose filename would traverse if used naively.
    r = client.post(
        "/parse-multipart",
        data={"yaml": yaml, "formats": "svg"},
        files=[("files", ("../../etc/passwd.png", TINY_PNG, "image/png"))],
    )
    # Should resolve as the basename `passwd.png` and succeed — proving the
    # filename was sanitised, not honored as a path.
    assert r.status_code == 200, r.text
    assert "data:image/png;base64," in r.json()["svg"]


def test_parse_multipart_rejects_empty_filename(client):
    # Sending an upload with an empty filename must not be accepted —
    # the sidecar can't write that to the tempdir under any sensible
    # name. FastAPI's validator will often catch this as a 422 before
    # reaching our handler; we also raise 400 from the handler. Either
    # client-side error code is fine; what matters is "not 200".
    r = client.post(
        "/parse-multipart",
        data={"yaml": SIMPLE_YAML, "formats": "svg"},
        files=[("files", ("", TINY_PNG, "image/png"))],
    )
    assert r.status_code in (400, 422)


def test_parse_returns_structured_bom(client):
    r = client.post("/parse", json={"yaml": SIMPLE_YAML, "formats": ["tsv"]})
    assert r.status_code == 200
    body = r.json()
    bom = body["bom"]
    assert isinstance(bom, list) and len(bom) > 0
    # Each row is a dict-like record. Don't pin specific keys (engine
    # may evolve) but at minimum row 0 must have something.
    assert isinstance(bom[0], dict) and len(bom[0]) > 0


def test_parse_supports_html_and_gv_formats(client):
    r = client.post(
        "/parse", json={"yaml": SIMPLE_YAML, "formats": ["html", "gv"]}
    )
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["html"] and "<html" in body["html"].lower()
    # WireViz emits an undirected graph (`graph { ... }`), not `digraph`.
    assert body["gv"] and body["gv"].lstrip().startswith("graph ")


def test_parse_rejects_unknown_format(client):
    r = client.post(
        "/parse", json={"yaml": SIMPLE_YAML, "formats": ["pdf", "svg"]}
    )
    assert r.status_code == 400
    assert "pdf" in r.json()["detail"].lower()


def test_spool_streams_uploads_without_buffering(client, monkeypatch):
    # Regression: addresses PR review feedback about reading uploads with
    # upload.file.read() (full payload into memory). The fix uses
    # shutil.copyfileobj — verify that the streaming path is actually
    # taken by stubbing copyfileobj and asserting it's called.
    import shutil as _shutil

    from wireviz_gui_sidecar import app as sidecar_app

    calls: list[tuple[str, int]] = []
    real_copy = _shutil.copyfileobj

    def spy_copyfileobj(src, dst, *a, **kw):
        # Capture that we were called with a non-trivial source. The
        # source object is upload.file (a SpooledTemporaryFile-like).
        calls.append(("copy", id(src)))
        return real_copy(src, dst, *a, **kw)

    monkeypatch.setattr(sidecar_app.shutil, "copyfileobj", spy_copyfileobj)

    r = client.post(
        "/parse-multipart",
        data={"yaml": YAML_WITH_IMAGE, "formats": "svg"},
        files=[("files", ("cross-section.png", TINY_PNG, "image/png"))],
    )
    assert r.status_code == 200
    assert len(calls) == 1, "exactly one upload should have been streamed"
